# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_import_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_base_import_wizard(object):
    def setupUi(self, base_import_wizard):
        base_import_wizard.setObjectName("base_import_wizard")
        base_import_wizard.resize(658, 420)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.wizardPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.portfolio_added_label = QtWidgets.QLabel(self.wizardPage1)
        self.portfolio_added_label.setObjectName("portfolio_added_label")
        self.gridLayout.addWidget(self.portfolio_added_label, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.wizardPage1)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_project_button = QtWidgets.QPushButton(self.groupBox)
        self.add_project_button.setObjectName("add_project_button")
        self.gridLayout_2.addWidget(self.add_project_button, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.add_project_label = QtWidgets.QLabel(self.groupBox)
        self.add_project_label.setObjectName("add_project_label")
        self.gridLayout_2.addWidget(self.add_project_label, 2, 0, 1, 1)
        self.create_portfolio_label = QtWidgets.QLabel(self.groupBox)
        self.create_portfolio_label.setObjectName("create_portfolio_label")
        self.gridLayout_2.addWidget(self.create_portfolio_label, 1, 0, 1, 1)
        self.create_portfolio_button = QtWidgets.QPushButton(self.groupBox)
        self.create_portfolio_button.setObjectName("create_portfolio_button")
        self.gridLayout_2.addWidget(self.create_portfolio_button, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.added_projects_table = QtWidgets.QTableWidget(self.wizardPage1)
        self.added_projects_table.setObjectName("added_projects_table")
        self.added_projects_table.setColumnCount(0)
        self.added_projects_table.setRowCount(0)
        self.gridLayout.addWidget(self.added_projects_table, 2, 0, 1, 1)
        base_import_wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.wizardPage2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.create_series_item_button = QtWidgets.QPushButton(self.groupBox_2)
        self.create_series_item_button.setObjectName("create_series_item_button")
        self.gridLayout_3.addWidget(self.create_series_item_button, 2, 2, 1, 1)
        self.create_series_item_label = QtWidgets.QLabel(self.groupBox_2)
        self.create_series_item_label.setObjectName("create_series_item_label")
        self.gridLayout_3.addWidget(self.create_series_item_label, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.create_series_label = QtWidgets.QLabel(self.groupBox_2)
        self.create_series_label.setObjectName("create_series_label")
        self.gridLayout_3.addWidget(self.create_series_label, 1, 0, 1, 1)
        self.create_series_button = QtWidgets.QPushButton(self.groupBox_2)
        self.create_series_button.setObjectName("create_series_button")
        self.gridLayout_3.addWidget(self.create_series_button, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.series_added_label = QtWidgets.QLabel(self.wizardPage2)
        self.series_added_label.setObjectName("series_added_label")
        self.gridLayout_4.addWidget(self.series_added_label, 1, 0, 1, 1)
        self.added_series_item_table = QtWidgets.QTableWidget(self.wizardPage2)
        self.added_series_item_table.setObjectName("added_series_item_table")
        self.added_series_item_table.setColumnCount(0)
        self.added_series_item_table.setRowCount(0)
        self.gridLayout_4.addWidget(self.added_series_item_table, 2, 0, 1, 1)
        base_import_wizard.addPage(self.wizardPage2)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.wizardPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.wizardPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 1, 1, 1)
        self.select_datamap_button = QtWidgets.QPushButton(self.groupBox_3)
        self.select_datamap_button.setObjectName("select_datamap_button")
        self.gridLayout_6.addWidget(self.select_datamap_button, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 2, 1, 1, 1)
        self.select_gmpp_datamap_button = QtWidgets.QPushButton(self.groupBox_3)
        self.select_gmpp_datamap_button.setObjectName("select_gmpp_datamap_button")
        self.gridLayout_6.addWidget(self.select_gmpp_datamap_button, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 3, 1, 1, 1)
        self.select_transposed_master_button = QtWidgets.QPushButton(self.groupBox_3)
        self.select_transposed_master_button.setObjectName("select_transposed_master_button")
        self.gridLayout_6.addWidget(self.select_transposed_master_button, 3, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imported_datamap_table = QtWidgets.QTableWidget(self.wizardPage)
        self.imported_datamap_table.setRowCount(3)
        self.imported_datamap_table.setColumnCount(2)
        self.imported_datamap_table.setObjectName("imported_datamap_table")
        self.imported_datamap_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.imported_datamap_table)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 0, 1, 1)
        base_import_wizard.addPage(self.wizardPage)

        self.retranslateUi(base_import_wizard)
        QtCore.QMetaObject.connectSlotsByName(base_import_wizard)

    def retranslateUi(self, base_import_wizard):
        _translate = QtCore.QCoreApplication.translate
        base_import_wizard.setWindowTitle(_translate("base_import_wizard", "Wizard"))
        self.portfolio_added_label.setText(_translate("base_import_wizard", "PORTFOLIO ADDED"))
        self.add_project_button.setText(_translate("base_import_wizard", "Add Project"))
        self.add_project_label.setText(_translate("base_import_wizard", "Add Project to Portfolio"))
        self.create_portfolio_label.setText(_translate("base_import_wizard", "Create Portfolio"))
        self.create_portfolio_button.setText(_translate("base_import_wizard", "Create"))
        self.label_12.setText(_translate("base_import_wizard", "1. Portfolio & Projects"))
        self.create_series_item_button.setText(_translate("base_import_wizard", "Add Series Item"))
        self.create_series_item_label.setText(_translate("base_import_wizard", "Add Series Item to Series"))
        self.create_series_label.setText(_translate("base_import_wizard", "Create Series"))
        self.create_series_button.setText(_translate("base_import_wizard", "Create"))
        self.label_13.setText(_translate("base_import_wizard", "2. Series"))
        self.series_added_label.setText(_translate("base_import_wizard", "SERIES ADDED"))
        self.label_7.setText(_translate("base_import_wizard", "3. Datamap Files"))
        self.label.setText(_translate("base_import_wizard", "Select a datamap CSV file"))
        self.select_datamap_button.setText(_translate("base_import_wizard", "Select"))
        self.label_2.setText(_translate("base_import_wizard", "Select a GMPP datamap CSV file"))
        self.select_gmpp_datamap_button.setText(_translate("base_import_wizard", "Select"))
        self.label_3.setText(_translate("base_import_wizard", "Select a transposed_master CSV file"))
        self.select_transposed_master_button.setText(_translate("base_import_wizard", "Select"))

