# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer_ui/base_import_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_baseWizard(object):
    def setupUi(self, baseWizard):
        baseWizard.setObjectName("baseWizard")
        baseWizard.resize(658, 420)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.wizardPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.wizardPage1)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.wizardPage1)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_project_button = QtWidgets.QPushButton(self.groupBox)
        self.add_project_button.setObjectName("add_project_button")
        self.gridLayout_2.addWidget(self.add_project_button, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.add_project_label = QtWidgets.QLabel(self.groupBox)
        self.add_project_label.setObjectName("add_project_label")
        self.gridLayout_2.addWidget(self.add_project_label, 2, 0, 1, 1)
        self.create_portfolio_label = QtWidgets.QLabel(self.groupBox)
        self.create_portfolio_label.setObjectName("create_portfolio_label")
        self.gridLayout_2.addWidget(self.create_portfolio_label, 1, 0, 1, 1)
        self.create_portfolio_button = QtWidgets.QPushButton(self.groupBox)
        self.create_portfolio_button.setObjectName("create_portfolio_button")
        self.gridLayout_2.addWidget(self.create_portfolio_button, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.portfolio_added_label = QtWidgets.QLabel(self.wizardPage1)
        self.portfolio_added_label.setObjectName("portfolio_added_label")
        self.gridLayout.addWidget(self.portfolio_added_label, 1, 0, 1, 1)
        baseWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.wizardPage2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.create_series_item_button = QtWidgets.QPushButton(self.groupBox_2)
        self.create_series_item_button.setObjectName("create_series_item_button")
        self.gridLayout_3.addWidget(self.create_series_item_button, 2, 2, 1, 1)
        self.create_series_item_label = QtWidgets.QLabel(self.groupBox_2)
        self.create_series_item_label.setObjectName("create_series_item_label")
        self.gridLayout_3.addWidget(self.create_series_item_label, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.create_series_label = QtWidgets.QLabel(self.groupBox_2)
        self.create_series_label.setObjectName("create_series_label")
        self.gridLayout_3.addWidget(self.create_series_label, 1, 0, 1, 1)
        self.create_series_button = QtWidgets.QPushButton(self.groupBox_2)
        self.create_series_button.setObjectName("create_series_button")
        self.gridLayout_3.addWidget(self.create_series_button, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        baseWizard.addPage(self.wizardPage2)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.wizardPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.wizardPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 1, 1, 1)
        self.select_datamap_button = QtWidgets.QPushButton(self.groupBox_3)
        self.select_datamap_button.setObjectName("select_datamap_button")
        self.gridLayout_6.addWidget(self.select_datamap_button, 1, 2, 1, 1)
        self.selected_datamap_file_label = QtWidgets.QLabel(self.groupBox_3)
        self.selected_datamap_file_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_datamap_file_label.setObjectName("selected_datamap_file_label")
        self.gridLayout_6.addWidget(self.selected_datamap_file_label, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 2, 1, 1, 1)
        self.select_gmpp_datamap_button = QtWidgets.QPushButton(self.groupBox_3)
        self.select_gmpp_datamap_button.setObjectName("select_gmpp_datamap_button")
        self.gridLayout_6.addWidget(self.select_gmpp_datamap_button, 2, 2, 1, 1)
        self.selected_gmpp_datamap_file_label = QtWidgets.QLabel(self.groupBox_3)
        self.selected_gmpp_datamap_file_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_gmpp_datamap_file_label.setObjectName("selected_gmpp_datamap_file_label")
        self.gridLayout_6.addWidget(self.selected_gmpp_datamap_file_label, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 3, 1, 1, 1)
        self.select_transposed_master_button = QtWidgets.QPushButton(self.groupBox_3)
        self.select_transposed_master_button.setObjectName("select_transposed_master_button")
        self.gridLayout_6.addWidget(self.select_transposed_master_button, 3, 2, 1, 1)
        self.selected_transposed_master_file_label = QtWidgets.QLabel(self.groupBox_3)
        self.selected_transposed_master_file_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_transposed_master_file_label.setObjectName("selected_transposed_master_file_label")
        self.gridLayout_6.addWidget(self.selected_transposed_master_file_label, 3, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        baseWizard.addPage(self.wizardPage)

        self.retranslateUi(baseWizard)
        QtCore.QMetaObject.connectSlotsByName(baseWizard)

    def retranslateUi(self, baseWizard):
        _translate = QtCore.QCoreApplication.translate
        baseWizard.setWindowTitle(_translate("baseWizard", "Wizard"))
        self.add_project_button.setText(_translate("baseWizard", "Select"))
        self.add_project_label.setText(_translate("baseWizard", "Add Project to Portfolio"))
        self.create_portfolio_label.setText(_translate("baseWizard", "Create Portfolio"))
        self.create_portfolio_button.setText(_translate("baseWizard", "Select"))
        self.label_12.setText(_translate("baseWizard", "1. Portfolio & Projects"))
        self.portfolio_added_label.setText(_translate("baseWizard", "PORTFOLIO ADDED"))
        self.create_series_item_button.setText(_translate("baseWizard", "Select"))
        self.create_series_item_label.setText(_translate("baseWizard", "Create Series Item"))
        self.create_series_label.setText(_translate("baseWizard", "Create Series"))
        self.create_series_button.setText(_translate("baseWizard", "Select"))
        self.label_13.setText(_translate("baseWizard", "2. Series"))
        self.label_7.setText(_translate("baseWizard", "3. Datamap Files"))
        self.label.setText(_translate("baseWizard", "Select a datamap CSV file"))
        self.select_datamap_button.setText(_translate("baseWizard", "Select"))
        self.selected_datamap_file_label.setText(_translate("baseWizard", "TextLabel"))
        self.label_2.setText(_translate("baseWizard", "Select a GMPP datamap CSV file"))
        self.select_gmpp_datamap_button.setText(_translate("baseWizard", "Select"))
        self.selected_gmpp_datamap_file_label.setText(_translate("baseWizard", "TextLabel"))
        self.label_3.setText(_translate("baseWizard", "Select a transposed_master CSV file"))
        self.select_transposed_master_button.setText(_translate("baseWizard", "Select"))
        self.selected_transposed_master_file_label.setText(_translate("baseWizard", "TextLabel"))

